openapi: 3.0.1
info:
  title: '@jupiterone/graph-red-hat-quay'
  description: A JupiterOne Integration for ingesting data of the Red Hat Quay
  x-cortex-git:
    github:
      repository: JupiterOne/graph-red-hat-quay
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-red-hat-quay'
